flywheelsports/hydra

index.js
package.json

if it was provided in the message URL
For example: 
```
b8277c82699a83db4e965831e189c095@hello-service:[get]/v1/hello/greeting
```
was getting load balanced rather than being directed to the specific message instance.

makeAPIRequest wasn't using the serviceID

---

index.js
package.json

This allows for users to specify a DNS name inside the hydra config branch:
```
"hydra": {
"serviceName": "hydra-router",
"serviceDescription": "Service Router",
"serviceIP": "dockerhost",
"servicePort": 5353,
```
This will also allow hydra-enabled services to run in docker containers started with the `--add-host` parameter:
```
docker run -d -p 5353:80 --add-host dockerhost:$HOST_IP --workdir=/usr/src/app -v ~/usr/local/etc/hydra-router:/usr/src/app/config --name hydra-router flywheelsports/fwsp-hydra-router:0.11.3'
```

New DNS resolve for serverIP

---

index.js

@emadum fix for the following promise warning:
```
(node:5771) Warning: a promise was created in a handler at /Users/cjustiniano/dev/flywheelsports/fwsp-hydra-router/node_modules/fwsp-hydra/index.js:96:24 but was not returned from it, see http://goo.gl/rRqMUw
```

Eric's patch for promise warning

---

index.js
package.json

PR to switch from random load balancing to a deterministic model where the service instance which has most recently reported presence status is favored. The premise is that instance which which have not recently reported presence are more likely to have experienced a fatal issue.
_makeAPIRequest now supports retries if a service endpoint returns an error. When that happens another service instance is immediately selected as a retry target.

deterministic service instance selection with retry logic 

---

index.js
package.json

When a DNS name was used in the config.serviceIP field hydra was allowing the promise to resolve before properly updating.  Thre premature promise resolve was causing the serviceIP to not be properly set on initialization.

fix for name-based serverIP

---

documentation.md
index.js
package.json

This PR improves the handling of connecting to Redis.
- pass options from hydra.redis config entry to redis.createClient
- Extracted retry strategy to _redisRetryStrategy (so the retry strategy can be easily overridden by extending Hydra)
- Options for _redisRetryStrategy are passed in via the hydra.redis.retry_strategy config entry, since redis.createClient requires a function for that option. This is the only option that won't be passed through unmodified to redis.createClient.

allow more redis connection options

---

index.js

redis.delete method does not exist. Using redis.del method instead.
Updating old routes during service initialization.

Fixing _flushRoutes method. Updating old routes during service initialization.

---

index.js
package.json

This was done to match our ELK stack logging which uses `msg` rather than `message`.

Hydra logging now uses msg field

---

index.js
package.json

pRequest has an issue where it doesn't return the status code of its request. This makes it unusable by hydra-router and probably not a good idea elsewhere.  This PR removes the one place in hydra where pRequest was used.

experimental removal of prequest

---

index.js

The Accept header does not allow you to specify a charset. We most use the Accept-Charset header instead.
Please see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset

HTTP header Accept incorrectly used

---

plugin.js

From what I can tell plugins do not necessarily need options to be passed in. Currently if no `hydra.plugins[plugin-name]` is provided in the configuration then the plugin initialization throws the error `Unhandled rejection TypeError: Cannot read property [plugin-name] of undefined`
This PR safely accesses `hydra.plugins[plugin-name]` and if it doesn't exist then defaults to an empty object.
My preference would be to use [pathOr](http://ramdajs.com/docs/#pathOr) from Ramda.js or [get](https://lodash.com/docs/4.17.4#get) from lodash, but didn't want to add new dependencies without permission.

provide default for this.opts in plugins

---

index.js

While parsing the memory object, the character \n remains as the start of the properties "heapTotal", "heapUsed", "external".
Please see detailed issue (node: 7.x):
"memory": {
"rss": 59314176,
"\nheapTotal": 35631104,
"\nheapUsed": 21309544,
"\nexternal": 699713
}...
Now fixed:
"memory": {
"rss": 51007488,
"heapTotal": 21999616,
"heapUsed": 18682792,
"external": 74640
}...

Fixing \n char issue on memory object (node7.x)

---

index.js

Properly set initialized flag to false after shutdown.

Set initialized = false on shutdown

---

index.js

As discussed, introduced a check if port is already used, when assigning a random service port
Furthermore a fixed port range can be defined in config for random port assignment, for example
"servicePort": "8080-8090"
Checking for ports is currently infinitely until a free port is found, so service won't start up until a free port is found. 
Let me know your thoughts

Check for unassigned ports when retrieving random service port

---

index.js
specs/test.js

This allows tests to know when shutdown has completed as opposed to waiting for two seconds before proceeding to the next test which dramatically decreases the time it takes for tests to run.

hydra.shutdown() returns promise

---

index.js
lib/umfmessage.js
package.json

Note:  optional `sendOpts` to `hydra.makeAPIRequest` intentionally override UMF message timeouts.

request timeout support for umf messages

---

lib/server-request.js

Hey @cjus, couple days ago I asked you to upgrade the Express version for hydra-express due to an error when posting to services data with special and/or non-latin chars. Apparently it wasn't the express but rather the request object. Specifically body length. Getting length of the buffer fixes that...

Correct request body length

---

index.js
lib/server-request.js
package.json
specs/test.js

This PR seeks to improve the initialization process by offering an additional way of initializing hydra beyond the use of a configuration file and object.
The init function currently accepts a config parameter which can be an object or string. If it's a string then the string is expected to point to a file path for a configuration file. If the config parameter is an object then hydra will attempt to use the object members for initialization.
This PR adds the possibility of passing a config parameter of null or undefined.  Doing so will initiate the following flow:
* If the config is null then a new config is created with default values.
* Redis will then be expected to exists locally unless specified.
* A check is made for process.env.HYDRA_REDIS_URL. If defined then the config redis.url …

Improve hydra initialization process

---

index.js
lib/server-request.js
lib/utils.js
package.json
specs/test.js

* Hydra now supports the use of DNS service names. To use this feature simply add a `serviceDNS` entry to the hydra branch of your service configuration. 
```
{
"hydra": {
"serviceDNS": "hello-service",
"servicePort": 5000,
:
}
}
```
If that entry is present Hydra will ignore the serviceIP field.  This feature will be useful where hydra-enabled services are load balanced by and external load balancer such as NginX or Docker swarm orchestration.
* The algorithm that hydra used to load balance requests using hydra.makeAPIRequest (also used by Hydra-router!) worked by looking at available service instances and sorting them based on when they most recently updated their presence and selecting the top entry. The idea there was that services that recently reported health are less likely to be …

DNS and load balancing improvements

---

lib/server-response.js

I added a way to handle HTTP-StatusCodes for which there is no key in the ServerResponse.STATUS-object (i.e. '403').

Handling for unknown HTTP-Status

---

index.js
lib/umfmessage.js
package.json

Requests containing @ characters started failing after I updated to a recent hydra-router version. E.g. `/v1/service/setEmail/eric@flywheelsports.com`.
I haven't tested this change extensively, but it has worked with everything I did try.

allow @ characters in api routes

---

index.js
lib/cache.js
package-lock.json
package.json

This PR is for an important optimization in Hydra core.
The  `_checkServicePresence` method is one of the most utilized internal functions in hydra.   It's called by functions interested in knowing whether a particular service is available.  Under the hood, the function first queries Redis for keys related to a named service. The code then proceeds to query additional information for each of the returned service instances. Because this data is stored in Redis as a stringified JSON object, the returned data must be parsed to a restored JavaScript object.  Each returned object is then pushed onto an array and returned.
Although those operations are blazing fast, they're executed everytime presence information is needed. Which has the potential to be quite often!
The place those operations …

Support for cached calls.

---

index.js
package-lock.json
package.json

* Introduces use of the Redis scan command to replace the keys command #152 
* During _updatePresence two writes to Redis were eliminated.
* Use the Redis driver batch command instead of multi in strategic places.

Redis optimizations to reduce writes and make use of scan instead of keys

---

index.js

Just fix up the documentation a bit to reflect to current new reality of the bahvior.  Notable the optional parameter and that it can throw a reject() upon a Redis error.

L176 : Fix JSDOC on how _checkServiccePresence behaves

---

index.js

If the array was cached we were not returning a new random array and some code was dependent on array[0] being a random element each call.  Although not the most elegant solution for huge # of services -- it's certainly concise and "good enough" for anything normal (say 500 or less instances).

I177 - Return proper randomzied array each call

---

index.js
specs/test.js

Calling init() more than once it bad mojo — let’s protect that by doing a reject() if called more than once .
Added the check and also added a unit test to cover it....

I5-multiple Init() should generate an error reject() promise

---

index.js

I was struggling with hydra-integration plugin and found out that the promise chain was blocked when a plugin fails to load

Fixed promise chain blocking when plugin error

---

index.js

On shutdown, reset instance ID. This will allow proper: **init -> shutdown -> init -> shutdown** workflows. 
Without it, the hydra-integration tests won't pass ;(

reset instance ID on shutdown

---

index.js
package.json

This PR passes the `options` argument through to [node_redis's `duplicate` call](https://github.com/NodeRedis/node_redis#clientduplicateoptions-callback). In this case, I need to pass `{detect_buffers: true}` on the cloned connection to make proper use of the DUMP/RESTORE Redis commands.
This is something that would not be necessary if we migrated Hydra to `ioredis`, which has a more elegant API for handling buffers.
We should probably also add the `callback` argument, to allow maximum flexibility, which if present uses a non-blocking version of the call.

pass options through to redis duplicate call
