index.js
package.json

if HTTP method is not specified in message  field.

patched makeAPIRequest to return error

---

index.js
package.json

_connectToRedis now returns a promise. The default Redis reconnection duration is now reduced from one minute to 15 seconds.

improved initialization handling to address issue #34

---

index.js
package.json

- changed redis.createClient to redis.duplicate (closes #54)
- fixed HYDRA_REDIS_DB issue and removed redundant db select

Fixes for RedisConnection

---

index.js
package.json

update to resolve init call with current config object in case it was loaded from Redis

update to resolve init with current config object

---

.eslintrc
index.js
package.json

* add eslint dependencies
* added getClonedRedisClient
* Updated dependencies
* Updated .eslintrc

New getClonedRedisClient and dependency refresh

---

package.json

Update to included PR#82

---

index.js
package.json

Removed health check for diskspace and changed health update interval to 5 seconds.
Closes #89

Swapped out the request module for the node-fetch

---

index.js

Returning response text if response is not JSON.

Properly handling non json responses

---

specs/test.js

@cjus great job with 1.2.3! I'm just starting to take a look and saw that some tests weren't passing. Planning on looking deeper into how the testing is set up!

fix test logic

---

lib/utils.js
package.json

Add missing Utils.stringHash function

---

index.js

```javascript
// hydra.js
import hydra from 'hydra'
hydra.init({...})
export default hydra;
```
```javascript
// service.js
import hydra from './hydra.js';
hydra.getServices()
.then(...)
.catch(...); // Throws 'No Redis Connection'
hydra.makeAPIRequest({...})
.then(...)
.catch(...); // Throws 'Cannot read property 'keys' of null (this.redisdb)'
```
Methods that return promises can wait for initialization to complete before processing. Or alert the end user that `hydra.init()` was never invoked.
```javascript
import hydra from 'hydra';
hydra.init({...});
hydra.getServices()
.then(...) // WORKS!
.catch(...);
hydra.makeAPIRequest({...})
.then(...) // WORKS!
.catch(...);
```
```javascript
import hydra from 'hydra';
hydra.getServices()
.then(...)
.catch(...); // throws 'You must call …
```

[Feature] - Wait for initialization before calling methods

---

index.js

New PR, thanks for your hint with git reset!
If a fixed service port if given in config, no checks will be performed
Port groups and ranges allow now ports between 1 and 65535

If a fixed service port if given in config, no port checks will be performed

---

.travis.yml
README.md

README.md - adding pass/fail badge.

.travis.yml - turning off email notifications on builds.

---

index.js
lib/config.js
lib/redis-connection.js
lib/umfmessage.js
lib/utils.js
package.json
specs/test.js

Hydra now passes HTTP headers on makeAPIRequest. Hydra is now smaller with less external dependencies.

Refactoring, cleanup, bug fixes

---

index.js
package.json

Code cleanup - because clean code matters!

Comment cleanup and minor changes.

---

index.js
package-lock.json
package.json

So they can potentially serve websites.

Ensure that services include web routes

---

index.js
lib/server-request.js
lib/server-response.js
package.json

when request method is PATCH, allow JSON data to be sent in body
add HTTP 202 (ACCEPTED) status code to status codes list

add missing features - HTTP PATCH support, HTTP 202 response code

---

.gitignore
package-lock.json
package.json
specs/test.js

Added instanbul with a new "coverage" package.json script and removed the duplicate tests in tests.js as well as used @description for standardized JSDOC ..

Issue_178 : Add code coverage and cleanup Unit Tests a bit

---

index.js

Just add a check to see if a supplied instance id is actually in the list of instances whose presence is still good. Also fixed up a bit of JSDOC error on what is returned.

L174 : Check instanceId is “alive” before sending..

---

index.js
package-lock.json
package.json

Also restructured a bit to ensure that original message is used in lrem redis call.

 _markQueueMessage to handle adding reason to umf messages with .bdy

---

lib/cache.js
specs/cache.test.js
specs/index.test.js

Added full coverage to the Cache lib and also tweaked it a bit to make it slightly more effecient and IMHO more readable.. and it still passes all the tests.. Aren’t unit tests awesome!!  :)
I also renamed the generic test.js to be specific for index.test.js since that is what it is testing ..

Add more unit test coverage for Cache and cleaned it up a bit

---

index.js
lib/utils.js
specs/utils.test.js

Added coverage for Utils .. but also fixed a typo with shuffleArray which was shuffeArray…

Add unit tests for Utils and fix typo

---

lib/umfmessage.js
package-lock.json
specs/umfmessage.test.js

Added unit tests for umfMessage as a base line.  They could be more involved but at least its a start. 
@cjus -- Note while writing the tests I believe I noticed two bugs in the actual umfmessage.js code .. so please pay specific attention to that code changes I made and confirm my interpretation of what should be going on is right.  
Also -- not sure what to keep doing about that packages-lock.json file .. ??

Unit test umfmessage
